version: "3.7"

networks:
    app:
        driver: bridge

volumes:
    cache: {}
    postgres-data:

services:


    discovery-service:
        build:
            context: ./discovery-service
        networks:
            - app
        ports:
            - "8761:8761"

    zookeeper:
        image: confluentinc/cp-zookeeper:7.4.4
        networks:
            - app
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "22181:2181"

    kafka:
        image: confluentinc/cp-kafka:7.4.4
        networks:
            - app
        depends_on:
            - zookeeper
        ports:
            - "29092:29092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    api-gateway:
        build:
            context: ./api-gateway
        networks:
            - app
        ports:
            -   "8089:8089"
        depends_on:
            -   discovery-service

    redis:
        image: redis:7.2-rc-alpine
        networks:
            - app
        container_name: redis
        ports:
            -   "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass ZmRlZWRhc3Nl
        volumes:
            - cache:/data
        restart: always