spring:
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yaml
    enabled: true
  application:
    name: orders-service
  config:
    import: optional:file:.env[.properties]
  kafka:
    bootstrap-servers: localhost:29092
  datasource:
    url: jdbc:mysql://localhost:3308/orders-service?user=${MYSQL_USERNAME}&password=${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka