spring:
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yaml
    enabled: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: cart-service
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: ZmRlZWRhc3Nl
  config:
    import: optional:file:.env[.properties]
  kafka:
    bootstrap-servers: localhost:29092
  datasource:
    url: jdbc:mysql://localhost:3310/cart-service?user=user&password=password
    name: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
server:
  port: 8083

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
